name: ci
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: |
            node_modules
            .cache/Cypress
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test:ci
      - run: |
          git remote set-url origin https://git:${{ secrets.DEPLOY_GITHUB_TOKEN }}@github.com/sospedra/which-key-code.git
          yarn deploy
